server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Han-Jeong/msa_study_yml
#          uri: file:///Users/hann/study/test

