server:
  port: 0

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: msa_user
    password: test123


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple E-commerce.

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.example.user_service.client: DEBUG